"""Initial schema: all 10 tables

Revision ID: 10e0382919d5
Revises: 
Create Date: 2026-04-10 12:57:40.759433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10e0382919d5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('processed_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_identifier', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_scraped_external_id', sa.String(length=255), nullable=True),
    sa.Column('last_scraped_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_type', 'source_identifier', name='uq_source_type_identifier')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('telegram_chat_id', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('daily_enabled', sa.Boolean(), nullable=False),
    sa.Column('daily_hour', sa.Integer(), nullable=False),
    sa.Column('weekly_enabled', sa.Boolean(), nullable=False),
    sa.Column('weekly_day', sa.Integer(), nullable=False),
    sa.Column('weekly_hour', sa.Integer(), nullable=False),
    sa.Column('daily_min_confidence', sa.Float(), nullable=False),
    sa.Column('weekly_min_confidence', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_chat_id')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('digests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('digest_type', sa.String(length=20), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('window_end', sa.DateTime(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('telegram_message_id', sa.Integer(), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_url', sa.Text(), nullable=True),
    sa.Column('media_type', sa.String(length=50), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('embedding_vector', sa.LargeBinary(), nullable=True),
    sa.Column('minhash_signature', sa.LargeBinary(), nullable=True),
    sa.Column('dedup_cluster_id', sa.String(length=36), nullable=True),
    sa.Column('is_cluster_primary', sa.Boolean(), nullable=False),
    sa.Column('deduplicated_at', sa.DateTime(), nullable=True),
    sa.Column('category_scores_json', sa.JSON(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('entities_json', sa.JSON(), nullable=True),
    sa.Column('classified_at', sa.DateTime(), nullable=True),
    sa.Column('forwarded_from_channel', sa.String(length=255), nullable=True),
    sa.Column('forwarded_message_id', sa.String(length=255), nullable=True),
    sa.Column('raw_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_source_external_id')
    )
    op.create_index(op.f('ix_messages_status'), 'messages', ['status'], unique=False)
    op.create_table('user_knowledge',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entity_name', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('encounter_count', sa.Integer(), nullable=False),
    sa.Column('categories', sa.JSON(), nullable=True),
    sa.Column('embedding', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'canonical_name', name='uq_user_canonical_name')
    )
    op.create_table('user_sources',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'source_id')
    )
    op.create_table('digest_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('digest_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('rank_in_category', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['digest_id'], ['digests.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_categories',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('top_k', sa.Integer(), nullable=False),
    sa.Column('min_confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_categories')
    op.drop_table('digest_items')
    op.drop_table('user_sources')
    op.drop_table('user_knowledge')
    op.drop_index(op.f('ix_messages_status'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('digests')
    op.drop_table('categories')
    op.drop_table('users')
    op.drop_table('sources')
    op.drop_table('pipeline_runs')
    # ### end Alembic commands ###
